services:
  db-notificacion:
    image: mysql:8.0
    container_name: mysql_servidor_notificacion
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: notificacion_backend
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3309:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_db_notificacion:/var/lib/mysql

  workspace-notificacion:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_notificacion
    ports:
      - "8089:8089"
    depends_on:
      - db-notificacion
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./codigo-fuente:/app
    environment:
      - USUARIO_SERVICE_URL=http://34.231.120.127:8081
    working_dir: /app

networks:
  red_interna_proyecto:

volumes:
  persistencia_db_notificacion: